### PR TITLE
fix #3266

### LINKED ISSUE #3266: After recent Qiita update, "Principal Coordinate Analysis Biplot [pcoa_biplot] (qiime2 2022.11.1)" now fails
Error executing Principal Coordinate Analysis Biplot [pcoa_biplot]: ['Traceback (most recent call last):\n', ' File "/home/qiita/miniconda3/envs/qiime2-2022.11/lib/python3.8/site-packages/qiita_client/plugin.py", line 265, in call\n success, artifacts_info, error_msg = task(\n', ' File "/home/qiita/miniconda3/envs/qiime2-2022.11/lib/python3.8/site-packages/qiita_client/plugin.py", line 105, in call\n return self.function(qclient, server_url, job_id, output_dir)\n', ' File "/home/qiita/qiita_spots/qp-qiime2/qp_qiime2/qp_qiime2.py", line 536, in call_qiime2\n atype = Q2_QIITA_SEMANTIC_TYPE[str(q2artifact.type)]\n', 'KeyError: "PCoAResults % Properties('biplot')"\n']

Using 'Unweighted Unifrac PCoA results', and a collapsed, rarefied, 'relative frequency table'

--------------------

Reported by @ekunselman https://github.com/biocore/emperor/issues/814

### PR DESCRIPTION
**Pull request by antgonza**
This does the bare minimum to fix https://github.com/qiita-spots/qiita/issues/3266.

### CODE REVIEW

**Review by ElDeveloper — APPROVED** [review]
Looks good, I would suggest adding a comment linking to your explanation in the original issue. Up to you 👍

**Comment by ElDeveloper** [comment]
Wait!

**Comment by ElDeveloper** [comment]
Sorry for the confusion, I just remembered that EMPeror uses this property as a way to determine whether it should use `qiime emperor plot` or `qiime emperor biplot`. Coercing the type and removing the property will lead to an error from `qiime emperor plot`. The correct thing would be to use `qiime emperor biplot` when that property is present. Alternatively an additional flag can be passed to `qiime emperor plot` to ignore biplot arrows but I think that wouldn't be the expected behavior.

**Comment by antgonza** [comment]
I deployed this solution in qiita-rc and the command is working again, including the "summary" which is done [here](https://github.com/qiita-spots/qtp-diversity/blob/master/qtp_diversity/summary.py#L79) and perhaps the reason it works fine. 

As a reminder, we automatically summarize the QZA's in Qiita so we get something that the user can see without having to summarize it themselves. For example, a PCoA will be automatically summarized via the lines above but the user can still use `emperor plot` in case they want to use any of the non default parameters. BTW we don't currently expose the `emperor biplot` command in Qiita but we can - I'll check it and issue another PR if it's possible.

**Review by ElDeveloper — APPROVED** [review]
Thanks for checking on qiita-rc! This sounds good to me then.

**Pull request merged**
